version: "3.4"

services:
  downloader:
    image: cdalvaro/gaia-downloader:latest
    build:
      context: ./
      dockerfile: downloader.Dockerfile
    container_name: gaia_downloader
    command: --cluster ALL --exclude "Platais 8" --verbose
    restart: on-failure
    environment:
      DB_HOST: db
      DB_NAME: gaia
      DB_USER: gaia
      DB_PASSWORD: gaia
    depends_on:
      - db

  db:
    image: postgres:12.4
    container_name: gaia_db
    restart: always
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gaia
      POSTGRES_USER: gaia
      POSTGRES_PASSWORD: gaia
      POSTGRES_INITDB_ARGS: "--data-checksums"
    volumes:
      - postgres-data:/var/lib/postgresql/data:Z
      - ./assets/postgres:/docker-entrypoint-initdb.d:ro

volumes:
  postgres-data:
    name: gaia-postgres-data
